project:
  type: website

website:
  title: "Design Artifacts Course"
  description: "Welcome to the Design Artifacts Course"
format:
  html:
    theme:
      - zephyr
      - brand
    css: styles.css




